<html>
<head>
<title>threadexception.py</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #c678dd;}
.s1 { color: #abb2bf;}
.s2 { color: #5c6370;}
.s3 { color: #98c379;}
.s4 { color: #56b6c2;}
</style>
</head>
<body bgcolor="#282c34">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
threadexception.py</font>
</center></td></tr></table>
<pre><span class="s0">import </span><span class="s1">threading</span>
<span class="s0">import </span><span class="s1">traceback</span>
<span class="s0">import </span><span class="s1">warnings</span>
<span class="s0">from </span><span class="s1">types </span><span class="s0">import </span><span class="s1">TracebackType</span>
<span class="s0">from </span><span class="s1">typing </span><span class="s0">import </span><span class="s1">Any</span>
<span class="s0">from </span><span class="s1">typing </span><span class="s0">import </span><span class="s1">Callable</span>
<span class="s0">from </span><span class="s1">typing </span><span class="s0">import </span><span class="s1">Generator</span>
<span class="s0">from </span><span class="s1">typing </span><span class="s0">import </span><span class="s1">Optional</span>
<span class="s0">from </span><span class="s1">typing </span><span class="s0">import </span><span class="s1">Type</span>

<span class="s0">import </span><span class="s1">pytest</span>


<span class="s2"># Copied from cpython/Lib/test/support/threading_helper.py, with modifications.</span>
<span class="s0">class </span><span class="s1">catch_threading_exception:</span>
    <span class="s2">&quot;&quot;&quot;Context manager catching threading.Thread exception using 
    threading.excepthook. 
 
    Storing exc_value using a custom hook can create a reference cycle. The 
    reference cycle is broken explicitly when the context manager exits. 
 
    Storing thread using a custom hook can resurrect it if it is set to an 
    object which is being finalized. Exiting the context manager clears the 
    stored object. 
 
    Usage: 
        with threading_helper.catch_threading_exception() as cm: 
            # code spawning a thread which raises an exception 
            ... 
            # check the thread exception: use cm.args 
            ... 
        # cm.args attribute no longer exists at this point 
        # (to break a reference cycle) 
    &quot;&quot;&quot;</span>

    <span class="s0">def </span><span class="s1">__init__(self) -&gt; </span><span class="s0">None</span><span class="s1">:</span>
        <span class="s2"># See https://github.com/python/typeshed/issues/4767 regarding the underscore.</span>
        <span class="s1">self.args: Optional[</span><span class="s3">&quot;threading._ExceptHookArgs&quot;</span><span class="s1">] = </span><span class="s0">None</span>
        <span class="s1">self._old_hook: Optional[Callable[[</span><span class="s3">&quot;threading._ExceptHookArgs&quot;</span><span class="s1">], Any]] = </span><span class="s0">None</span>

    <span class="s0">def </span><span class="s1">_hook(self, args: </span><span class="s3">&quot;threading._ExceptHookArgs&quot;</span><span class="s1">) -&gt; </span><span class="s0">None</span><span class="s1">:</span>
        <span class="s1">self.args = args</span>

    <span class="s0">def </span><span class="s1">__enter__(self) -&gt; </span><span class="s3">&quot;catch_threading_exception&quot;</span><span class="s1">:</span>
        <span class="s1">self._old_hook = threading.excepthook</span>
        <span class="s1">threading.excepthook = self._hook</span>
        <span class="s0">return </span><span class="s1">self</span>

    <span class="s0">def </span><span class="s1">__exit__(</span>
        <span class="s1">self,</span>
        <span class="s1">exc_type: Optional[Type[BaseException]],</span>
        <span class="s1">exc_val: Optional[BaseException],</span>
        <span class="s1">exc_tb: Optional[TracebackType],</span>
    <span class="s1">) -&gt; </span><span class="s0">None</span><span class="s1">:</span>
        <span class="s0">assert </span><span class="s1">self._old_hook </span><span class="s0">is not None</span>
        <span class="s1">threading.excepthook = self._old_hook</span>
        <span class="s1">self._old_hook = </span><span class="s0">None</span>
        <span class="s0">del </span><span class="s1">self.args</span>


<span class="s0">def </span><span class="s1">thread_exception_runtest_hook() -&gt; Generator[</span><span class="s0">None</span><span class="s1">, </span><span class="s0">None</span><span class="s1">, </span><span class="s0">None</span><span class="s1">]:</span>
    <span class="s0">with </span><span class="s1">catch_threading_exception() </span><span class="s0">as </span><span class="s1">cm:</span>
        <span class="s0">yield</span>
        <span class="s0">if </span><span class="s1">cm.args:</span>
            <span class="s0">if </span><span class="s1">cm.args.thread </span><span class="s0">is not None</span><span class="s1">:</span>
                <span class="s1">thread_name = cm.args.thread.name</span>
            <span class="s0">else</span><span class="s1">:</span>
                <span class="s1">thread_name = </span><span class="s3">&quot;&lt;unknown&gt;&quot;</span>
            <span class="s1">msg = </span><span class="s3">f&quot;Exception in thread </span><span class="s4">{</span><span class="s1">thread_name</span><span class="s4">}\n\n</span><span class="s3">&quot;</span>
            <span class="s1">msg += </span><span class="s3">&quot;&quot;</span><span class="s1">.join(</span>
                <span class="s1">traceback.format_exception(</span>
                    <span class="s1">cm.args.exc_type, cm.args.exc_value, cm.args.exc_traceback,</span>
                <span class="s1">)</span>
            <span class="s1">)</span>
            <span class="s1">warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))</span>


<span class="s1">@pytest.hookimpl(hookwrapper=</span><span class="s0">True</span><span class="s1">, trylast=</span><span class="s0">True</span><span class="s1">)</span>
<span class="s0">def </span><span class="s1">pytest_runtest_setup() -&gt; Generator[</span><span class="s0">None</span><span class="s1">, </span><span class="s0">None</span><span class="s1">, </span><span class="s0">None</span><span class="s1">]:</span>
    <span class="s0">yield from </span><span class="s1">thread_exception_runtest_hook()</span>


<span class="s1">@pytest.hookimpl(hookwrapper=</span><span class="s0">True</span><span class="s1">, tryfirst=</span><span class="s0">True</span><span class="s1">)</span>
<span class="s0">def </span><span class="s1">pytest_runtest_call() -&gt; Generator[</span><span class="s0">None</span><span class="s1">, </span><span class="s0">None</span><span class="s1">, </span><span class="s0">None</span><span class="s1">]:</span>
    <span class="s0">yield from </span><span class="s1">thread_exception_runtest_hook()</span>


<span class="s1">@pytest.hookimpl(hookwrapper=</span><span class="s0">True</span><span class="s1">, tryfirst=</span><span class="s0">True</span><span class="s1">)</span>
<span class="s0">def </span><span class="s1">pytest_runtest_teardown() -&gt; Generator[</span><span class="s0">None</span><span class="s1">, </span><span class="s0">None</span><span class="s1">, </span><span class="s0">None</span><span class="s1">]:</span>
    <span class="s0">yield from </span><span class="s1">thread_exception_runtest_hook()</span>
</pre>
</body>
</html>